### ISSUE TITLE
support -mcpu=cortex-m0plus

### ISSUE THREAD

**Issue by sebseb7** [esden/summon-arm-toolchain#55]
http://sourceware.org/ml/binutils/2012-03/msg00298.html
http://patchwork.ozlabs.org/patch/151088/

**Comment by esden** [comment]
Hi,

Thank you for your suggestion. Your issue report is not very verbose. I would appreciate if you took a tiny bit more time to explain your request and how you would like it solved.

That said, if you read the top of the README file of this project. SAT is not maintained any more as the there is a very good binary toolchain released by ARM themselves: https://launchpad.net/gcc-arm-embedded

Even if this project was in active development I am not sure I would accept a temporary patch like this, considering that the support for m0+ will be added in not too long future to GCC and binutils. The correct solution here is that you patch this feature temporarily for yourself in your own SAT build. The m0+ support will automatically "appear" in SAT when the up stream packages enable it.

Thus I am closing this issue.

Cheers,
Piotr

Edit: Damn I just realized how old that issue is. ;) Well this project was maintained at that time. But the comment still holds, I hope the m0+ support is finally in mainline. ;)
